/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ujianpraktek;

import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Karyawan extends javax.swing.JFrame {
    
    //prosedur/method untuk mengosongkan form
    private void kosong_form() {
        textNIK.setEditable(true);
        
        textNIK.setText(null);
        textNama.setText(null);
//        textJabatan.setText(null);
        comboDivisi.setSelectedItem(this);
        comboJabatan.setSelectedItem(this);
        textHP.setText(null);
        textEmail.setText(null);
        textAlamat.setText(null);
    }
    
    //prosedur menampilkan data dalam tabel
    private void tampil_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Jabatan");
        model.addColumn("Divisi");
        model.addColumn("No Handphone");
        model.addColumn("Email");
        model.addColumn("Alamat");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM karyawan";
            java.sql.Connection conn =(Connection)connect.connectDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
//          //pemakaian array
            while (res.next()){
                model.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7)});
            }
            
            tabelData.setModel(model);
        }catch(SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * Creates new form Karyawan
     */
    public Karyawan() {
        initComponents();
        tampil_data();
        kosong_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textNIK = new javax.swing.JTextField();
        textNama = new javax.swing.JTextField();
        comboJabatan = new javax.swing.JComboBox<>();
        textHP = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textAlamat = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        buttonTambah = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonBatal = new javax.swing.JButton();
        ButtonSimpan = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();
        comboDivisi = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATA KARYAWAN");
        setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("DATA KARYAWAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 16, -1, -1));

        jLabel1.setText("NIK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 106, -1, -1));

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 153, -1, -1));

        jLabel4.setText("Divisi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 191, -1, -1));

        jLabel5.setText("Jabatan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 227, -1, -1));

        jLabel6.setText("No Handphone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 268, -1, -1));

        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 312, -1, -1));

        jLabel8.setText("Alamat");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 356, -1, -1));
        getContentPane().add(textNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 91, 320, -1));
        getContentPane().add(textNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 135, 320, -1));

        getContentPane().add(comboJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 221, 320, -1));
        getContentPane().add(textHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 265, 320, -1));

        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 309, 320, -1));
        getContentPane().add(textAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 353, 320, -1));

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelData);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 461, 703, 149));

        buttonTambah.setBackground(new java.awt.Color(0, 0, 153));
        buttonTambah.setForeground(new java.awt.Color(255, 255, 255));
        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 414, -1, -1));

        ButtonEdit.setBackground(new java.awt.Color(0, 153, 0));
        ButtonEdit.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 414, -1, -1));

        ButtonHapus.setBackground(new java.awt.Color(153, 0, 0));
        ButtonHapus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 414, -1, -1));

        ButtonBatal.setText("Batal");
        ButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBatalActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 414, -1, -1));

        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 414, -1, -1));

        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 626, -1, -1));

        comboDivisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engineering", "Marketing", "HR", "Creative" }));
        comboDivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDivisiActionPerformed(evt);
            }
        });
        getContentPane().add(comboDivisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 320, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        kosong_form();
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO karyawan VALUES ('"+textNIK.getText()+"', '"+textNama.getText()+"', '"+comboDivisi.getSelectedItem()+"', '"+comboJabatan.getSelectedItem()+"', '"+textHP.getText()+"', '"+textEmail.getText()+"', '"+textAlamat.getText()+"')";
            java.sql.Connection conn = (Connection)connect.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            String email = textEmail.getText();
            String noHP = textHP.getText();
            if (!email.contains("@gmail.com")) {
                JOptionPane.showMessageDialog(null, "Alamat Email Salah!");
                textEmail.setText(null);
            } else if (!noHP.contains("08")){
                JOptionPane.showMessageDialog(null, "Berikan Format Nomor yang Benar!");
                textHP.setText(null);
            }
            else {
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Berhasil Ditambahkan");
                tampil_data();
                kosong_form();
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE karyawan SET nik ='"+textNIK.getText()+"', nama ='"+textNama.getText()+"', jabatan='"+comboJabatan.getSelectedItem()+"', divisi='"+comboDivisi.getSelectedItem()+"', handphone = '"+textHP.getText()+"', email='"+textEmail.getText()+"', alamat='"+textAlamat.getText()+"' WHERE nik = '" + textNIK.getText() +"'";
            java.sql.Connection conn = (Connection)connect.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_data();
        kosong_form();
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        // TODO add your handling code here:
        int baris = tabelData.rowAtPoint(evt.getPoint());
        
        String NIK = tabelData.getValueAt(baris, 1).toString();
        textNIK.setText(NIK);
        
        String nama = tabelData.getValueAt(baris, 2).toString();
        textNama.setText(nama);
        
        String divisi = tabelData.getValueAt(baris, 3).toString();
        comboDivisi.setSelectedItem(divisi);
        
        String jabatan = tabelData.getValueAt(baris, 4).toString();
        comboJabatan.setSelectedItem(jabatan);
        
        String noHP = tabelData.getValueAt(baris, 5).toString();
        textHP.setText(noHP);
        
        String email = tabelData.getValueAt(baris, 6).toString();
        textEmail.setText(email);
        
        String alamat = tabelData.getValueAt(baris, 7).toString();
        textAlamat.setText(alamat);
        
    }//GEN-LAST:event_tabelDataMouseClicked

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM karyawan WHERE nik = '" + textNIK.getText() +"'";
            java.sql.Connection conn = (Connection)connect.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_data();
        kosong_form();
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void ButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBatalActionPerformed
        // TODO add your handling code here:
        kosong_form();
        
    }//GEN-LAST:event_ButtonBatalActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
//        String email = textEmail.getText();
//        if (!email.contains("@")) {
//            JOptionPane.showMessageDialog(null, "Tambahkan alamat email");
//        } else {
//            JOptionPane.showMessageDialog(null, "Email Sudah Benar");
//        }
    }//GEN-LAST:event_textEmailActionPerformed

    private void comboDivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDivisiActionPerformed
        // TODO add your handling code here:
        if(comboDivisi.getSelectedItem().equals("Engineering")){
            comboJabatan.removeAllItems();
            comboJabatan.setSelectedItem(null);
            comboJabatan.addItem("Software Engineer");
            comboJabatan.addItem("FrontEnd Develover");
            comboJabatan.addItem("Machine Learning Engineer");
            comboJabatan.addItem("Data Analyst");
            comboJabatan.addItem("BackEnd Developer");
        } else if (comboDivisi.getSelectedItem().equals("Marketing")){
            comboJabatan.removeAllItems();
            comboJabatan.setSelectedItem(null);
            comboJabatan.addItem("Advertising Manager");
            comboJabatan.addItem("Public Relations Manager");
            comboJabatan.addItem("Promotions Manager");
            comboJabatan.addItem("Brand Manager");
            comboJabatan.addItem("Community Manager");
        } else if (comboDivisi.getSelectedItem().equals("Creative")){
            comboJabatan.removeAllItems();
            comboJabatan.setSelectedItem(null);
            comboJabatan.addItem("UI/UX Designer");
            comboJabatan.addItem("Graphic Designer");
            comboJabatan.addItem("Photographer");
            comboJabatan.addItem("VideoGrapher");
        } else if (comboDivisi.getSelectedItem().equals("HR")){
            comboJabatan.removeAllItems();
            comboJabatan.setSelectedItem(null);
            comboJabatan.addItem("Recruitment & Hiring");
            comboJabatan.addItem("Organization development");
            comboJabatan.addItem("Performance appraisal");
            comboJabatan.addItem("People development");
            comboJabatan.addItem("Compensation & benefit");
        }
    }//GEN-LAST:event_comboDivisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBatal;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JComboBox<String> comboDivisi;
    private javax.swing.JComboBox<String> comboJabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelData;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textHP;
    private javax.swing.JTextField textNIK;
    private javax.swing.JTextField textNama;
    // End of variables declaration//GEN-END:variables
}
